# 🔴 Task 10: Introduction to NumPy (arrays, basic operations)


#### 1.Create a 1D NumPy array containing the integers from 0 to 9.


In [15]:
import numpy as np
array1=np.arange(0,10,dtype=int)
print("list of integers from 0 to 9\n:",array1)

list of integers from 0 to 9
: [0 1 2 3 4 5 6 7 8 9]


#### 2.Create a 2D NumPy array (3x3) containing random integers between 1 and 20.


In [17]:
array2=np.random.randint(1,20, size=(3,3))
print("Random integers between 1 to 20:\n" ,array2)

Random integers between 1 to 20:
 [[ 3 15 15]
 [13  5  9]
 [ 5 16  7]]


#### 3.Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.


In [19]:
array3=np.ones((2,3,4))
print("Numpy array with dimension (2,3,4),filled with ones is \n", array3)

Numpy array with dimension (2,3,4),filled with ones is 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


#### 4.Add two 1D arrays element-wise.
 

In [20]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=x+y
print("Addition of 2 1D arrays:",z)

Addition of 2 1D arrays: [ 6  8 10 12]


#### 5.Multiply two 2D arrays element-wise.


In [22]:
array1=np.array([[2,3,4],
                 [5,6,7]])

array2=np.array([[1,2,1],
                [2,1,1]])
multiply=array1*array2
print("Multiplication of two 2D arrays \n", multiply)


Multiplication of two 2D arrays 
 [[ 2  6  4]
 [10  6  7]]


#### 6.Calculate the dot product of two matrices.


In [13]:
array1=np.array([[2,3,4],
                 [5,6,7]])

array2=np.array([[1,2,1],
                [2,1,1],
                 [0,1,2]])

dotproduct=array1 @ array2
print(dotproduct)


[[ 8 11 13]
 [17 23 25]]


#### 7.Calculate the mean, median, and standard deviation of a 1D array.


In [23]:
array1=np.array([1,2,3,4,5])
x=np.mean(array1)
print("Mean=",x)
y=np.median(array1)
print("Median",y)
z=np.std(array1)
print("Standard Deviation",z)

Mean= 3.0
Median 3.0
Standard Deviation 1.4142135623730951


#### 8.Find the maximum and minimum values in a 2D array.


In [25]:
array1=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

x=np.max(array1)
print(x)
y=np.min(array1)
print(y)

9
1


#### 9.Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.


In [29]:
import numpy as np
array1=np.random.normal(0,1,1000)
print(array1)

[-1.75618159e-02  1.97021669e+00 -5.97347687e-01 -6.05726845e-01
 -5.77385860e-01 -5.54777437e-01 -9.85351903e-01  7.73956720e-01
 -2.58354181e-01  5.87757294e-01  1.82458667e-01  9.99465797e-01
  8.56837986e-01  4.00671050e-01  9.38928948e-01 -3.04724970e-01
  1.23132287e+00 -2.33164662e+00  3.07432457e-02 -4.94754175e-01
  5.89868161e-01 -2.63369623e+00 -3.12323405e-01 -1.28536011e-01
 -3.63432250e-02  3.92876402e-01 -5.79538839e-01 -2.19633533e-01
  1.29041297e-01  1.83684841e+00  8.52753528e-01 -6.85559824e-01
  1.00993410e+00  6.65930845e-01  4.17635425e-02  1.15484116e+00
 -7.76444246e-02 -8.56729899e-01 -1.03459026e+00  1.59200708e+00
  2.95644169e-01  2.18228896e-01  1.00742164e+00 -1.94293808e-01
 -9.41456799e-01  4.20835964e-01 -5.83228205e-01  7.90853651e-01
  3.09779332e-01  4.81552189e-02 -8.91522493e-01  2.23142115e+00
  7.28350516e-01  1.39197912e+00 -6.44936508e-01  6.05368008e-01
  1.23921847e+00 -9.38832165e-02  1.86254504e-01 -5.34535311e-01
 -9.40440853e-01 -4.16219

#### 10.Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50.


In [27]:
array1=np.random.randint(10,50,size=(5,5))  # Size shows the number of rows and columns
print(array1)

[[41 16 43 16 35]
 [36 26 42 31 27]
 [40 31 29 44 15]
 [48 22 30 28 27]
 [21 21 47 31 17]]


#### 11.Calculate the cumulative sum of a 1D array.


In [30]:
array1=np.array([2,4,6,10])
x=np.sum(array1)
print(x)

22


#### 12.Compute the correlation coefficient matrix of a 2D array.


In [32]:
array1=np.array([[2,2,4],[4,6,6],[6,8,8]])
y=np.corrcoef(array1)
print(y)

[[1.  0.5 0.5]
 [0.5 1.  1. ]
 [0.5 1.  1. ]]


#### 13.Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.
 

In [33]:
rolls=np.random.randint(1,7,size=1000)
frequency = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0}
for roll in rolls:
    frequency[roll] += 1
for number in range(1, 7):
    print("Number " + str(number) + ": " + str(frequency[number]) + " times")


Number 1: 188 times
Number 2: 152 times
Number 3: 177 times
Number 4: 156 times
Number 5: 173 times
Number 6: 154 times
