# 🔴 Task 11: NumPy advanced operations (indexing, slicing, broadcasting)


## Indexing and Slicing


#### 7.Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).


In [101]:
import numpy as np
array1=np.arange(1,37).reshape(6,6)
print("2D ARRAY \n",array1)

print("\n")

x=array1[1:3,1:3]
print("2x2 sub-array \n",x)

2D ARRAY 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


2x2 sub-array 
 [[ 8  9]
 [14 15]]


#### 8.From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.


In [102]:
array1=np.arange(1,13).reshape(3,2,2) # Array will be divided into 3 blocks, each block will have 2 rows and 1 column
print("3D array\n",array1)

print("\n")

x=array1[0:2,:,1]
print("Extracted rows and columns \n",x)


3D array
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


Extracted rows and columns 
 [[2 4]
 [6 8]]


#### 9.Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].


In [103]:
array1=np.random.randint(1,33,size=(8,4))
print("Array of integers \n",array1)
print("\n")
print("Extracted elements \n",array1[[1,3,4,6]])    # Fancy indexing extracts the number of rows in specific order 


Array of integers 
 [[31 32  8 32]
 [26 26  8 23]
 [ 3 31 16 10]
 [12 20  4  7]
 [ 8 14 14 22]
 [13 28  7  9]
 [32 19 11 28]
 [12 27  9  5]]


Extracted elements 
 [[26 26  8 23]
 [12 20  4  7]
 [ 8 14 14 22]
 [32 19 11 28]]


#### 10.Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].



In [104]:
array1=np.random.randint(1,21,size=(5,4))
print("2D ARRAY \n",array1)
print("\n")
print("Extracted rows and columns \n",array1[[0,2,3],:][:,[1,3]]) 

2D ARRAY 
 [[16  8 20 11]
 [20 12 10 14]
 [20 10  4 18]
 [17  5 18 13]
 [12  2 17 20]]


Extracted rows and columns 
 [[ 8 11]
 [10 18]
 [ 5 13]]


#### 11.From a 1D array of random integers, extract all elements that are greater than 8.



In [106]:
array1=np.random.randint(5,20,size=10)
print("1D array\n",array1)

x=array1[array1 > 8]
print("Elements that are > 8\n",x)

1D array
 [17  5 19 18  7 19  6  6 13 14]
Elements that are > 8
 [17 19 18 19 13 14]


#### 12.Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.


In [109]:
array1=np.random.randint(1,21,size=(6,6))
print(" 2D ARRAY \n",array1)
print("\n")

x=array1[array1 > 13]
print("Elements that are > 13\n",x)
print("\n")

array1[array1>13] = 0
print("Zeros inplace of elements > 13 \n",array1)


 2D ARRAY 
 [[11 19 14 18 13  8]
 [ 8 14 12 18 11 16]
 [15  3  9 10  2  1]
 [ 2 18 11  8 17  5]
 [16  8  4  7 10  1]
 [11 13  1 16  3  5]]


Elements that are > 13
 [19 14 18 14 18 16 15 18 17 16 16]


Zeros inplace of elements > 13 
 [[11  0  0  0 13  8]
 [ 8  0 12  0 11  0]
 [ 0  3  9 10  2  1]
 [ 2  0 11  8  0  5]
 [ 0  8  4  7 10  1]
 [11 13  1  0  3  5]]


## Broadcasting

#### 5.Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).


In [112]:
array1=np.array([1,2,3])
print("1D array \n",array1)

array2=np.arange(0,12).reshape(4,3)
print("2D array \n",array2)

x=array1+array2
print("\n Addition of 1D array to each row of 2D array row\n", x)

1D array 
 [1 2 3]
2D array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 Addition of 1D array to each row of 2D array row
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


#### 6.Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).


In [113]:
array1=np.arange(0,9).reshape(3,3)
print("2D array\n",array1)

print("\n")

array2=np.arange(3).reshape(3)
print("1D array \n",array2)

print("\n")

Multiply=array1 * array2
print("Multiplication of both arrays\n",Multiply)

2D array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


1D array 
 [0 1 2]


Multiplication of both arrays
 [[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]


#### 7.Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.


In [116]:
arr1=np.arange(0,3).reshape(3,1)
print("2D array of shape (3,1)\n",arr1)

print("\n")

arr2=np.arange(0,4).reshape(1,4)
print("2D array of shape (1,4)\n",arr2)

Element_wise_sum=arr1+arr2
print("Element wise sum \n",Element_wise_sum)


2D array of shape (3,1)
 [[0]
 [1]
 [2]]


2D array of shape (1,4)
 [[0 1 2 3]]
Element wise sum 
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


#### 8.Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [117]:
arr1=np.arange(24).reshape(2,3,4)
print(" 3D array of shape (2, 3, 4)\n",arr1)

print("\n")

arr2=np.arange(12).reshape(3,4)
print("2D array of shape (3, 4) \n",arr2)

print("\n")

sum=arr1+arr2
print("sum of both\n",sum)

 3D array of shape (2, 3, 4)
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


2D array of shape (3, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


sum of both
 [[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]]


## More Examples

#### 7.Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.


In [120]:
import numpy as np
arr1=np.arange(25).reshape(5,5)
print("2D array\n",arr1)

print("\n")

arr2=np.array([1,2,3])
print("1D ARRAY\n",arr2)

print("\n")

x=arr1[2::,::2]
print("Extracted rows and columns \n",x)

print("\n")

y=x+arr2
print("Final Result \n",y)

2D array
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1D ARRAY
 [1 2 3]


Extracted rows and columns 
 [[10 12 14]
 [15 17 19]
 [20 22 24]]


Final Result 
 [[11 14 17]
 [16 19 22]
 [21 24 27]]


#### 8.From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [121]:
arr1=np.arange(6).reshape(3,2,1)
print("3D array of shape (3, 2, 1)\n",arr1)
print("\n")

arr2 = np.array([[1], [2]])
print("sub-array",arr2)
print("\n")

subtract=arr1-arr2
print("After subtraction\n",subtract)

3D array of shape (3, 2, 1)
 [[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]


sub-array [[1]
 [2]]


After subtraction
 [[[-1]
  [-1]]

 [[ 1]
  [ 1]]

 [[ 3]
  [ 3]]]


#### 9.Given a 2D array, extract the diagonal elements and create a 1D array.


In [122]:
arr1=np.arange(9).reshape(3,3)
print("2D array\n",arr1)

x=np.diagonal(arr1)
print("diagonal elements\n",x)

2D array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
diagonal elements
 [0 4 8]


#### 10.Use slicing to reverse the order of elements in each row of a 2D array.


In [123]:
arr1=np.arange(9).reshape(3,3)
print("2D array.\n",arr1)

x=arr1[:,::-1]
print("Reverse of array\n",x)

2D array.
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Reverse of array
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


#### 11.Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

In [124]:
arr1=np.arange(210).reshape(7,6,5)
print("3D array of shape (7, 6, 5)\n",arr1)
print("\n")
sub_array=np.arange(24).reshape(2,3,4)
print("sub-array of shape (2, 3, 4)\n",sub_array)
print("\n")

arr2=np.array([1,2,3,4])
print("1D array of shape (4,)\n",arr2)
y=sub_array+arr2
print("Final Results \n",y)

3D array of shape (7, 6, 5)
 [[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]
  [ 25  26  27  28  29]]

 [[ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]
  [ 50  51  52  53  54]
  [ 55  56  57  58  59]]

 [[ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]
  [ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]]

 [[ 90  91  92  93  94]
  [ 95  96  97  98  99]
  [100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]

 [[120 121 122 123 124]
  [125 126 127 128 129]
  [130 131 132 133 134]
  [135 136 137 138 139]
  [140 141 142 143 144]
  [145 146 147 148 149]]

 [[150 151 152 153 154]
  [155 156 157 158 159]
  [160 161 162 163 164]
  [165 166 167 168 169]
  [170 171 172 173 174]
  [175 176 177 178 179]]

 [[180 181 182 183 184]
  [185 186 187 188 189]
  [190 191 192 193 194]
  [195 196 197 198 199]

#### 12.Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [126]:

array_2d = np.arange(15).reshape(3,5)
print("2D array \n",array_2d)

array_2d[-1,: ] = array_2d[0,: ] + array_2d[1,: ]

print("Modified list\n",array_2d)




2D array 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Modified list
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 5  7  9 11 13]]
